### ISSUE TITLE
22000804 홍석찬 프로젝트 아이디어 입니다!

### ISSUE THREAD

**Issue by redstonecold** [redstonecold/2021OSSL_MiniTeam#1]
주제 : 팀 출석 명단
기능 
 - text 파일 형태 : 
  날짜  학생명  출석여부
  21.05.19 김철수 O
  21.05.19 홍길동 O

 - Create :  위와 같이 날짜 학생명 출석여부가 들어간 한 line 생성
 - Read : 전체 .txt 파일 읽어오기 ( readlist(), listlist() )
 - Update : 출석여부 수정
 - Delete : 해당 line 삭제
 - 추가 검색 함수 : 날짜로 찾기, 학생명으로 찾기, 출석여부로 찾기
 - 추가 파일 관련 함수 : 파일 저장 함수, 파일 불러오기 함수 
 - 추가 helper function : selectMenu(), selectDataNo()

**Comment by redstonecold** [comment]
이렇게 comment 하는 건가?

**Comment by Diggydogg** [comment]
**아트 갤러리 crud project**

**미술 작품 갤러리 , 아티스트와 그 작품을 보여주는 하이퍼링크 로 갤러리 생성**


**C** : 작품 고유 번호 (생성 순으로 ),아티스트 이름, 작품 이름 , 작품 생성 날짜, 작품 사진 하이퍼 링크 (data type: int,str, str, str(or long int), str) ,, structure 로 새성 
R : 아티스트 이름이 null 이 아니면 읽기 , 아티스트 이름, 작품 이름 , 작품 생성 날짜, 작품 사진 순서대로,,
**U** : 아티스트나 작품이름 검색을 통해 찾기 (find func) 찾은후 작품 고유 번호대로 나열, 
(예시, 
1. 피카소 우는 여인 ,,,,
2. 앙리 마티즈 블루 ,,,,
3. 구스타프 클림트  키스  ,,,,
업데이트할 작품 번호를 선택하세요 :  1 
-> 이후 작품 고유 번호 빼고 자료 업데이트 가능

**D**:  delete 도 find 함수를 통해 찾은후 작품 번호를 통해 삭제 
이때, 아티스트 이름과 작품 번호를 null 로 세팅 

find func; 위에 설명 , (아티스트나 작품이름 검색을 통해 찾기 )

**M** : 메뉴, 위 함수들을 구현할수 있는 메뉴 옵션 보여주시 
예시 :
1. 갤러리 생성
2. 갤러리 모두  보기
3. 갤러리 업데이트
4. 갤러리 삭제 

**FI** : 파일 입출력, 작품 고유 번호 (생성 순으로 ),아티스트 이름, 작품 이름 , 작품 생성 날짜, 작품 사진 하이퍼 링크 (data type: int,str, str, str(or long int), str) 으로 저장 (gallery.txt)
**FO** :  파일 load, 시작할떄 gallery.txt 를 읽어오기

//아래 항목은 아직 확정 x

**작품 상세 설명 함수** : structure (작품명, 작품에 대한 간단한 설명 , str, str) // 어떻게 구현 할지 생각중
**아티스트 상세 설명**  : structure (아티스트 이름 , 아티스트 생애 설명 , str, str) 
 위 함수들은 포인터로 통해 구현? helper 함수들이 필요할 듯,,,,
